blank_issues_enabled: false
contact_links:
  - name: Join the iOS beta (TestFlight)
    url: https://testflight.apple.com/join/fPfRkrbH
    about: Get the latest iOS build to test.
  - name: Join the Android beta (Firebase)
    url: https://appdistribution.firebase.dev/i/7df9c87a09c55992
    about: Get the latest Android build to test.
