blank_issues_enabled: false
contact_links:
  - name: Questions & general feedback
    url: https://github.com/nour2063/earthPlace/discussions
    about: For open-ended feedback, questions, or ideas you're not sure about, start a discussion instead.
